import type { Metadata } from "next";
import { Roboto_Mono,Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable:"--font-poppins",
  subsets: ["latin"],
  weight: ["100","200","300","400", "500", "600", "700", "800", "900"],
})

// const roboto = Roboto({
//   variable: "--font-roboto",
//   subsets: ["latin"],
// });

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "URL Shortener",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
