events {} # needed even if empty

http {
    upstream backend_pool {
        server backend:5000; # syntax is host:port, no http
        # default config is round-robin
    }

    upstream frontend_pool {
        server frontend:3000;
    }
    
    server {
        listen 80;

        # nginx checks location from top to bottom in order:

        location = /health { # exact endpoint match with equal sign
            proxy_pass http://backend_pool; # automatically appends /health at end after :5000..., but wouldn't if we used a trailing slash like http://localhost:5000/
        }

        # backend
        location /api/ {
            proxy_pass http://backend_pool/; # left the trailing slash at end so that nginx strips /api and forwards the remaining of /api"/blah-blah-blah"
            proxy_set_header Host $host; # coz nginx strips the original host header by default, we need to set it back so that our backend can know the original host
            proxy_set_header X-Real-IP $remote_addr; # preserve client IP
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; # preserve client IP in case of multiple proxies
        }

        # frontend
        location / { # catch all
            proxy_pass http://frontend_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade; # needed for websocket support for nextjs hot reload
            proxy_set_header Connection "upgrade"; # needed for same reason
        }

    }
}